[default]
LOG_FILE_NAME = 'boomi_cicd'
LOG_LEVEL = 'INFO'
LOG_FORMAT = '[%(asctime)s] [%(levelname)s] [%(message)s] [--> %(pathname)s [%(process)d]:]'
LOG_FILE_LOCATION = '/tmp/'
encrypt_file_password = "PASSWORD"
